import { createContext, useContext, useState } from 'react'

const Ctx = createContext({ lang: 'EL', setLang: () => {} })

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(
    () => localStorage.getItem('soleia-lang') || 'EL'
  )
  function setLang(l) {
    setLangState(l)
    localStorage.setItem('soleia-lang', l)
  }
  return <Ctx.Provider value={{ lang, setLang }}>{children}</Ctx.Provider>
}

export function useLang() { return useContext(Ctx) }

export function useT() {
  const { lang } = useContext(Ctx)
  return translations[lang]
}

export const translations = {
  EN: {
    // Navbar
    nav_login: 'Log in',
    nav_sign_out: 'Sign out',
    nav_list_business: 'List your business',
    nav_notifications: 'Notifications',

    // SearchBar
    search_all_treatments: 'All treatments',
    search_anywhere: 'Anywhere in Cyprus',
    search_anytime: 'Any time',
    search_btn: 'Search',
    search_current_location: 'Current location',
    search_getting_location: 'Getting location…',
    search_popular_cities: 'Popular cities',
    search_today: 'Today',
    search_tomorrow: 'Tomorrow',
    search_time_label: 'Time',
    filter_tabs: ['All', 'Treatments', 'Venues', 'Professionals'],
    // Category display names (keys stay English for data matching)
    cat_display: {
      'Hair & styling': 'Hair & styling',
      'Nails': 'Nails',
      'Hair removal': 'Hair removal',
      'Eyebrows & eyelashes': 'Eyebrows & eyelashes',
      'Facials & skincare': 'Facials & skincare',
      'Massage': 'Massage',
      'Makeup': 'Makeup',
      'Aesthetics': 'Aesthetics',
      'Barbering': 'Barbering',
      'Spa & wellness': 'Spa & wellness',
      'Body & skin': 'Body & skin',
      'Tattoo & piercing': 'Tattoo & piercing',
      'Holistic health': 'Holistic health',
      'Dental': 'Dental',
    },
    // Time slots (English values used for state, these are display labels)
    time_slots: [
      { key: 'Any time',   label: 'Any time',   sub: null },
      { key: 'Morning',    label: 'Morning',    sub: '9am – 12pm' },
      { key: 'Afternoon',  label: 'Afternoon',  sub: '12pm – 5pm' },
      { key: 'Evening',    label: 'Evening',    sub: '5pm – 12am' },
    ],
    months: ['January','February','March','April','May','June','July','August','September','October','November','December'],
    days_short: ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],
    days_booking: ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'],
    locale: 'en-GB',

    // Home page
    home_hero_title: 'Book local selfcare services',
    home_hero_sub: 'Discover top-rated massage therapists, beauty artists, hair stylists and wellness coaches across Cyprus.',
    home_stats_count: '3,800+',
    home_stats_label: 'appointments booked',
    home_stats_area: 'Available across Cyprus',
    home_get_app: 'Get the app',
    home_recommended: 'Recommended',
    home_new: 'New to Soleia',
    home_featured: 'Featured',
    home_reviews: 'reviews',
    home_popular_searches: ['Massage', 'Lash extensions', 'Balayage', 'Yoga class', 'Manicure', 'Facial'],
    home_why: [
      { title: 'Verified providers',  desc: 'Every provider is reviewed and verified by our team before listing.' },
      { title: 'Instant booking',     desc: 'No calls, no waiting. Book and receive confirmation in seconds.' },
      { title: '4.9 average rating',  desc: 'Trusted by locals and tourists alike across all of Cyprus.' },
    ],
    home_cta_tag: 'For professionals',
    home_cta_title: ['Grow your client base', 'with Soleia'],
    home_cta_sub: 'Join 391 providers already booking clients through Soleia. Free to join — 0% commission for the first 3 months.',
    home_cta_btn: 'List your business',

    // Services page
    svc_tabs: ['Venues', 'Professionals'],
    svc_map_area: 'venues within map area',
    svc_results: 'results',
    svc_filters: 'Filters',
    svc_hide_map: 'Hide map',
    svc_show_map: 'Show map',
    // CATS values must match data .category field — keep English, translate display only
    svc_cats_labels: ['All', 'Massage', 'Beauty', 'Hair', 'Wellness'],
    svc_max_price: 'Max price',
    svc_city_label: 'City',
    svc_search_label: 'Search',
    svc_search_ph: 'treatments or names...',
    svc_no_results: 'No venues match your filters.',
    svc_clear_filters: 'Clear filters',
    // City display names (filter values stay English to match data)
    svc_cities_labels: ['All', 'Limassol', 'Nicosia', 'Paphos', 'Larnaca'],
    svc_reviews: 'reviews',
    svc_list_btn: 'List',
    svc_map_btn: 'Map',
    svc_featured: 'Featured',
    svc_deals: 'Deals',

    // Provider profile
    pp_back: 'Back to services',
    pp_about: 'About',
    pp_specialisations: 'Specialisations',
    pp_services_pricing: 'Services & pricing',
    pp_reviews: 'Reviews',
    pp_book_btn: 'Book',
    pp_book_now: 'Book now',
    pp_send_message: 'Send a message',
    pp_per_session: '/ session',
    pp_free_cancel: 'Free cancellation up to 24 hours',
    pp_instant_confirm: 'Instant confirmation',
    pp_secure_payment: 'Secure payment via Soleia',
    pp_not_charged: "You won't be charged yet",
    pp_verified_since: 'Verified since',
    pp_starting_from: 'Starting from',

    // Booking page
    book_steps: ['Date', 'Time', 'Details', 'Confirm'],
    book_select_date: 'Select a date',
    book_select_time: 'Select a time',
    book_your_details: 'Your details',
    book_review_confirm: 'Review & confirm',
    book_continue: 'Continue',
    book_back: 'Back',
    book_back_profile: 'Back to profile',
    book_full_name: 'Full name',
    book_email: 'Email address',
    book_phone: 'Phone number',
    book_notes: 'Notes for provider',
    book_optional: '(optional)',
    book_notes_ph: 'Any specific requests, health conditions, or preferences...',
    book_review_btn: 'Review booking',
    book_labels: ['Service', 'Provider', 'Date', 'Time', 'Duration', 'Location', 'Name', 'Email', 'Phone'],
    book_total: 'Total',
    book_payment_demo: 'Payment (demo)',
    book_stripe_note: 'Secure payment processed by Stripe. Your data is encrypted.',
    book_confirm_pay: 'Confirm & pay',
    book_processing: 'Processing...',
    book_summary_title: 'Booking summary',
    book_confirmed_title: 'Booking confirmed!',
    book_confirmed_with: 'Your appointment with',
    book_confirmed_for: 'is confirmed for',
    book_confirmed_at: 'at',
    book_confirmed_email_sent: 'A confirmation email has been sent to',
    book_total_paid: 'Total paid',
    book_back_home: 'Back to home',
    book_pick_date_hint: 'Select a date to continue',
    book_date_prefix: 'Continue —',

    // Footer
    footer_tagline: 'Discover. Book. Glow.',
    footer_desc: "Cyprus's platform for booking trusted local self-care services — beauty, wellness, and relaxation.",
    footer_services: 'Services',
    footer_company: 'Company',
    footer_contact: 'Contact',
    footer_service_links: ['Massage & Spa', 'Beauty Treatments', 'Hair Salon', 'Yoga & Wellness', 'Skin Care', 'Nail Art'],
    footer_company_links: ['About Us', 'For Providers', 'Blog', 'Careers', 'Press', 'Privacy Policy', 'Terms of Service'],
    footer_copyright: '© 2025 Soleia Cyprus. All rights reserved.',
    footer_made: 'Made with care in Cyprus',

    // Placeholder pages
    fav_title: 'Your Favourites',
    fav_desc: "Save the therapists and venues you love — they'll appear here for quick booking.",
    fav_explore_btn: 'Explore services',
    bk_title: 'Your Bookings',
    bk_desc: 'Once you book a treatment, your upcoming and past appointments will appear here.',
    bk_browse_btn: 'Browse services',
    prof_guest: 'Guest User',
    prof_location: 'Cyprus',
    prof_edit: 'Edit profile',
    prof_stat_bookings: 'Bookings',
    prof_stat_fav: 'Favourites',
    prof_stat_reviews: 'Reviews',
    prof_menu: [
      { label: 'Payment methods', sub: 'Manage cards & wallets' },
      { label: 'Preferences',     sub: 'Notifications, language' },
      { label: 'Help & support',  sub: 'FAQ, contact us' },
      { label: 'Sign out',        sub: null, danger: true },
    ],
    prof_version: 'Soleia Cyprus · v1.0',

    // Search modal
    search_modal_title: 'Search',
    search_modal_treatment_ph: 'Treatment, venue or professional...',
    search_modal_location_ph: 'Location',
    search_recent: 'Recent searches',
    search_clear: 'Clear',
    search_categories: 'Browse by category',

    // Results page
    results_filter_providers: 'Providers',
    results_filter_options: 'Options',
    results_filter_type: 'Service type',
    results_km: 'km',

    // Auth modal
    auth_title: 'Sign in or register',
    auth_subtitle: 'We need to verify it\'s you',
    auth_phone_label: 'Phone number',
    auth_phone_note: 'We\'ll send you a verification code. Standard rates may apply.',
    auth_continue: 'Continue',
    auth_or: 'Or',
    auth_email: 'Continue with email',
    auth_apple: 'Continue with Apple',
    auth_facebook: 'Continue with Facebook',
    auth_google: 'Continue with Google',
    auth_email_ph: 'Email address',
    auth_password_ph: 'Password',
    auth_back: 'Back',
    auth_signing_in: 'Please wait…',
    auth_check_email: 'Check your email to confirm your account, then come back to sign in.',
    auth_wrong_password: 'Wrong password. Please try again.',
    auth_otp_title: 'Verification code',
    auth_otp_sent: 'We sent a 6-digit SMS code to',
    auth_otp_verify: 'Verify',
  },

  EL: {
    // Navbar
    nav_login: 'Σύνδεση',
    nav_sign_out: 'Αποσύνδεση',
    nav_list_business: 'Καταχωρίστε',
    nav_notifications: 'Ειδοποιήσεις',

    // SearchBar
    search_all_treatments: 'Όλες οι θεραπείες',
    search_anywhere: 'Οπουδήποτε στην Κύπρο',
    search_anytime: 'Οποιαδήποτε ώρα',
    search_btn: 'Αναζήτηση',
    search_current_location: 'Τρέχουσα τοποθεσία',
    search_getting_location: 'Εντοπισμός…',
    search_popular_cities: 'Δημοφιλείς πόλεις',
    search_today: 'Σήμερα',
    search_tomorrow: 'Αύριο',
    search_time_label: 'Ώρα',
    filter_tabs: ['Όλα', 'Θεραπείες', 'Χώροι', 'Επαγγελματίες'],
    cat_display: {
      'Hair & styling': 'Μαλλιά & styling',
      'Nails': 'Νύχια',
      'Hair removal': 'Αποτρίχωση',
      'Eyebrows & eyelashes': 'Φρύδια & βλεφαρίδες',
      'Facials & skincare': 'Θεραπείες προσώπου',
      'Massage': 'Μασάζ',
      'Makeup': 'Μακιγιάζ',
      'Aesthetics': 'Αισθητική',
      'Barbering': 'Κουρείο',
      'Spa & wellness': 'Spa & ευεξία',
      'Body & skin': 'Σώμα & δέρμα',
      'Tattoo & piercing': 'Τατουάζ & piercing',
      'Holistic health': 'Ολιστική υγεία',
      'Dental': 'Οδοντιατρική',
    },
    time_slots: [
      { key: 'Any time',   label: 'Οποιαδήποτε ώρα', sub: null },
      { key: 'Morning',    label: 'Πρωί',             sub: '9πμ – 12μμ' },
      { key: 'Afternoon',  label: 'Απόγευμα',         sub: '12μμ – 5μμ' },
      { key: 'Evening',    label: 'Βράδυ',            sub: '5μμ – 12πμ' },
    ],
    months: ['Ιανουάριος','Φεβρουάριος','Μάρτιος','Απρίλιος','Μάιος','Ιούνιος','Ιούλιος','Αύγουστος','Σεπτέμβριος','Οκτώβριος','Νοέμβριος','Δεκέμβριος'],
    days_short: ['Δευ','Τρι','Τετ','Πεμ','Παρ','Σαβ','Κυρ'],
    days_booking: ['Κυρ','Δευ','Τρι','Τετ','Πεμ','Παρ','Σαβ'],
    locale: 'el-GR',

    // Home page
    home_hero_title: 'Κλείστε τοπικές υπηρεσίες αυτοφροντίδας',
    home_hero_sub: 'Ανακαλύψτε κορυφαίους θεραπευτές μασάζ, καλλιτέχνες ομορφιάς, κομμωτές και coaches ευεξίας σε όλη την Κύπρο.',
    home_stats_count: '3.800+',
    home_stats_label: 'ραντεβού κλεισμένα',
    home_stats_area: 'Διαθέσιμο σε όλη την Κύπρο',
    home_get_app: 'Κατεβάστε την εφαρμογή',
    home_recommended: 'Προτεινόμενα',
    home_new: 'Νέα στη Soleia',
    home_featured: 'Προτεινόμενο',
    home_reviews: 'αξιολογήσεις',
    home_popular_searches: ['Μασάζ', 'Βλεφαρίδες', 'Balayage', 'Yoga', 'Μανικιούρ', 'Facial'],
    home_why: [
      { title: 'Επαληθευμένοι πάροχοι', desc: 'Κάθε πάροχος αξιολογείται και επαληθεύεται από την ομάδα μας πριν την καταχώριση.' },
      { title: 'Άμεση κράτηση',          desc: 'Χωρίς κλήσεις, χωρίς αναμονή. Κλείστε και λάβετε επιβεβαίωση σε δευτερόλεπτα.' },
      { title: 'Μέση βαθμολογία 4.9',   desc: 'Εμπιστεύονται ντόπιοι και τουρίστες σε όλη την Κύπρο.' },
    ],
    home_cta_tag: 'Για επαγγελματίες',
    home_cta_title: ['Αναπτύξτε τη βάση πελατών σας', 'με τη Soleia'],
    home_cta_sub: 'Γίνετε μέλος από 391 παρόχους που ήδη κλείνουν πελάτες μέσω Soleia. Δωρεάν εγγραφή — 0% προμήθεια τους πρώτους 3 μήνες.',
    home_cta_btn: 'Καταχωρίστε την επιχείρησή σας',

    // Services page
    svc_tabs: ['Χώροι', 'Επαγγελματίες'],
    svc_map_area: 'χώροι στην περιοχή χάρτη',
    svc_results: 'αποτελέσματα',
    svc_filters: 'Φίλτρα',
    svc_hide_map: 'Απόκρυψη χάρτη',
    svc_show_map: 'Εμφάνιση χάρτη',
    svc_cats_labels: ['Όλα', 'Μασάζ', 'Ομορφιά', 'Μαλλιά', 'Ευεξία'],
    svc_max_price: 'Μέγιστη τιμή',
    svc_city_label: 'Πόλη',
    svc_search_label: 'Αναζήτηση',
    svc_search_ph: 'θεραπείες ή ονόματα...',
    svc_no_results: 'Κανένας χώρος δεν ταιριάζει με τα φίλτρα σας.',
    svc_clear_filters: 'Εκκαθάριση φίλτρων',
    svc_cities_labels: ['Όλα', 'Λεμεσός', 'Λευκωσία', 'Πάφος', 'Λάρνακα'],
    svc_reviews: 'αξιολογήσεις',
    svc_list_btn: 'Λίστα',
    svc_map_btn: 'Χάρτης',
    svc_featured: 'Προτεινόμενο',
    svc_deals: 'Προσφορές',

    // Provider profile
    pp_back: 'Πίσω στις υπηρεσίες',
    pp_about: 'Σχετικά',
    pp_specialisations: 'Ειδικότητες',
    pp_services_pricing: 'Υπηρεσίες & τιμές',
    pp_reviews: 'Αξιολογήσεις',
    pp_book_btn: 'Κράτηση',
    pp_book_now: 'Κλείστε τώρα',
    pp_send_message: 'Στείλτε μήνυμα',
    pp_per_session: '/ συνεδρία',
    pp_free_cancel: 'Δωρεάν ακύρωση έως 24 ώρες',
    pp_instant_confirm: 'Άμεση επιβεβαίωση',
    pp_secure_payment: 'Ασφαλής πληρωμή μέσω Soleia',
    pp_not_charged: 'Δεν θα χρεωθείτε ακόμα',
    pp_verified_since: 'Επαληθευμένος από',
    pp_starting_from: 'Από',

    // Booking page
    book_steps: ['Ημερομηνία', 'Ώρα', 'Στοιχεία', 'Επιβεβαίωση'],
    book_select_date: 'Επιλέξτε ημερομηνία',
    book_select_time: 'Επιλέξτε ώρα',
    book_your_details: 'Τα στοιχεία σας',
    book_review_confirm: 'Ανασκόπηση & επιβεβαίωση',
    book_continue: 'Συνέχεια',
    book_back: 'Πίσω',
    book_back_profile: 'Πίσω στο προφίλ',
    book_full_name: 'Πλήρες όνομα',
    book_email: 'Διεύθυνση email',
    book_phone: 'Τηλέφωνο',
    book_notes: 'Σημειώσεις για τον πάροχο',
    book_optional: '(προαιρετικό)',
    book_notes_ph: 'Ειδικά αιτήματα, υγειονομικές καταστάσεις ή προτιμήσεις...',
    book_review_btn: 'Ανασκόπηση κράτησης',
    book_labels: ['Υπηρεσία', 'Πάροχος', 'Ημερομηνία', 'Ώρα', 'Διάρκεια', 'Τοποθεσία', 'Όνομα', 'Email', 'Τηλέφωνο'],
    book_total: 'Σύνολο',
    book_payment_demo: 'Πληρωμή (demo)',
    book_stripe_note: 'Ασφαλής πληρωμή μέσω Stripe. Τα δεδομένα σας είναι κρυπτογραφημένα.',
    book_confirm_pay: 'Επιβεβαίωση & πληρωμή',
    book_processing: 'Επεξεργασία...',
    book_summary_title: 'Σύνοψη κράτησης',
    book_confirmed_title: 'Κράτηση επιβεβαιώθηκε!',
    book_confirmed_with: 'Η κράτησή σας με',
    book_confirmed_for: 'επιβεβαιώθηκε για',
    book_confirmed_at: 'στις',
    book_confirmed_email_sent: 'Επιβεβαίωση εστάλη στο',
    book_total_paid: 'Σύνολο πληρωθέν',
    book_back_home: 'Πίσω στην αρχική',
    book_pick_date_hint: 'Επιλέξτε ημερομηνία για να συνεχίσετε',
    book_date_prefix: 'Συνέχεια —',

    // Footer
    footer_tagline: 'Ανακάλυψε. Κλείσε. Λάμψε.',
    footer_desc: 'Η πλατφόρμα της Κύπρου για κρατήσεις αξιόπιστων τοπικών υπηρεσιών αυτοφροντίδας.',
    footer_services: 'Υπηρεσίες',
    footer_company: 'Εταιρεία',
    footer_contact: 'Επικοινωνία',
    footer_service_links: ['Μασάζ & Spa', 'Θεραπείες ομορφιάς', 'Κομμωτήριο', 'Yoga & Ευεξία', 'Περιποίηση δέρματος', 'Νύχια'],
    footer_company_links: ['Σχετικά με εμάς', 'Για Παρόχους', 'Blog', 'Καριέρα', 'Τύπος', 'Πολιτική απορρήτου', 'Όροι χρήσης'],
    footer_copyright: '© 2025 Soleia Κύπρος. Με επιφύλαξη παντός δικαιώματος.',
    footer_made: 'Φτιαγμένο με φροντίδα στην Κύπρο',

    // Placeholder pages
    fav_title: 'Τα Αγαπημένα σας',
    fav_desc: 'Αποθηκεύστε τους θεραπευτές και χώρους που αγαπάτε — θα εμφανίζονται εδώ για γρήγορη κράτηση.',
    fav_explore_btn: 'Εξερεύνηση υπηρεσιών',
    bk_title: 'Οι Κρατήσεις σας',
    bk_desc: 'Μόλις κλείσετε μια θεραπεία, τα επερχόμενα και παρελθοντικά ραντεβού σας θα εμφανίζονται εδώ.',
    bk_browse_btn: 'Περιήγηση υπηρεσιών',
    prof_guest: 'Επισκέπτης',
    prof_location: 'Κύπρος',
    prof_edit: 'Επεξεργασία προφίλ',
    prof_stat_bookings: 'Κρατήσεις',
    prof_stat_fav: 'Αγαπημένα',
    prof_stat_reviews: 'Αξιολογήσεις',
    prof_menu: [
      { label: 'Τρόποι πληρωμής',      sub: 'Διαχείριση καρτών & πορτοφολιών' },
      { label: 'Ρυθμίσεις',            sub: 'Ειδοποιήσεις, γλώσσα' },
      { label: 'Βοήθεια & υποστήριξη', sub: 'FAQ, επικοινωνήστε μαζί μας' },
      { label: 'Αποσύνδεση',           sub: null, danger: true },
    ],
    prof_version: 'Soleia Κύπρος · v1.0',

    // Search modal
    search_modal_title: 'Αναζήτηση',
    search_modal_treatment_ph: 'Θεραπεία, χώρος ή επαγγελματίας...',
    search_modal_location_ph: 'Τοποθεσία',
    search_recent: 'Πρόσφατες αναζητήσεις',
    search_clear: 'Διαγραφή',
    search_categories: 'Ανά κατηγορία',

    // Results page
    results_filter_providers: 'Παροχές',
    results_filter_options: 'Επιλογές',
    results_filter_type: 'Τύπος υπηρεσίας',
    results_km: 'χλμ',

    // Auth modal
    auth_title: 'Συνδεθείτε ή εγγραφείτε',
    auth_subtitle: 'Θα πρέπει να επαληθεύσουμε ότι είστε εσείς',
    auth_phone_label: 'Αριθμός τηλεφώνου',
    auth_phone_note: 'Θα σας στείλουμε έναν κωδικό επαλήθευσης. Ενδέχεται να ισχύουν τυποποιημένες χρεώσεις.',
    auth_continue: 'Συνέχεια',
    auth_or: 'Ή',
    auth_email: 'Συνέχεια με email',
    auth_apple: 'Συνέχεια με Apple',
    auth_facebook: 'Συνέχεια με Facebook',
    auth_google: 'Συνέχεια με Google',
    auth_email_ph: 'Διεύθυνση email',
    auth_password_ph: 'Κωδικός πρόσβασης',
    auth_back: 'Πίσω',
    auth_signing_in: 'Παρακαλώ περιμένετε…',
    auth_check_email: 'Ελέγξτε το email σας για επιβεβαίωση λογαριασμού, και επιστρέψτε για σύνδεση.',
    auth_wrong_password: 'Λάθος κωδικός. Δοκιμάστε ξανά.',
    auth_otp_title: 'Κωδικός επαλήθευσης',
    auth_otp_sent: 'Στείλαμε 6-ψήφιο SMS στο',
    auth_otp_verify: 'Επαλήθευση',
  },
}
